# Generated by Django 4.2.9 on 2024-01-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('vendor', models.CharField(max_length=100, verbose_name='厂商')),
                ('url', models.CharField(max_length=500, verbose_name='下载地址')),
                ('url_hash', models.CharField(max_length=100, unique=True, verbose_name='下载地址hash')),
                ('description', models.CharField(max_length=500, verbose_name='描述说明')),
                ('product', models.CharField(max_length=100, verbose_name='型号')),
                ('version', models.CharField(max_length=100, verbose_name='固件版本')),
                ('device_class', models.CharField(max_length=100, verbose_name='设备类型')),
                ('file_path', models.CharField(max_length=500, verbose_name='固件路径')),
                ('is_send', models.BooleanField(default=False, verbose_name='是否发送易识创建分析任务')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
